baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "Can I Blog Too"
theme = "hyde-x"
googleAnalytics = " UA-92008736-1"

[author]
    name = "Can I Blog Too"

# Enable Disqus integration
disqusShortname = "johngoldin"

publishDir = "../johngoldin.github.io"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"
[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/johngoldin"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/johngoldin"

[params]
    description = "Some of my personal projects with R"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.9.0"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"
    # Changes sidebar background and link/accent colours.
    # See below for more colour options.
    # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
    theme = "theme-base-08"
   
    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
    # license = "https://opensource.org/licenses/MIT"

    # Sidebar position
    # false, true, "left", "right"
    sidebar = "left"

    # Hide estimated reading time for posts.
    # Default (if omitted) is false.
    hideReadingTime = true
    
    # Displays under the author name in the sidebar, keep it short.
    # You can use markdown here.
    tagline = "Notes on this and that."
