baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "Can I Blog Too"
theme = "hyde"
googleAnalytics = ""
disqusShortname = ""
publishDir = "../johngoldin.github.io"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"
[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/johngoldin"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/johngoldin"

[params]
    description = "Some of my personal projects with R"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.9.0"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"
    themeColor = "theme-base-08"
   
    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

